export const text = {
  en: {
    "landing-heading": "Welcome To PV Sizer",
    "landing-text": `Proper sizing of an installation is an essential step to master, for this, we created a web app to make a pv system sizing just by inserting your location and desired charges and you, easy to use with precise results`,
    "start-btn": `Start Sizing`,
    "about-btn": `About Our Work`,
    "about-heading": "Our Work",
    "about-text": `Our work consists in realizing an interface for the dimensioning of the autonomous photovoltaic installations in any place in the world, we used HTML as a rendering language and JavaScript to receive and manage the data and do the calculations. The customer must enter the location where he wants to install perform his installation, the number of days of autonomy and its charges with their powers, the time of daily use. Then we used an API (Application Programming Interface) to retrieve the latitude and longitude of the place entered with which we will have the daily global sunshine from another API also specialized in this field.`,
    "code-btn": "See The Code",
    made: "Made By Zakaria BOURENANE & Yanis BENMEZIANE",
    copy: `ALL RIGHTS RESERVED 2020 <i class="fa fa-copyright" aria-hidden="true"></i>`,
    location: "Enter your location",
    "location-input": "Location",
    days: "Enter number day of autonomy",
    "days-input": "Days",
    add: "ADD A CHARGE",
    del: "DELETE A CHARGE",
    submit: "START",
    number: "Number (ex : 2)",
    power: "Load Power in Watt (ex : 120)",
    time: "Use Time In Hours (ex : 3)",
    angle: "Angle Of Inclination :",
    orientation: "Orientation :",
    "first-irradiance": "Solar Irradiance On The ",
    "second-irradiance": "Solar Irradiance On The ",
    energy: "Daily Energy Consomation :",
    "d-power": "Daily Power Consomation :",
    "pv-power": "PV Power :",
    "pv-battery": "Battery Capacity :",
    "choose-1": "Choose your PV module :",
    "choose-2": "Choose your battery model :",
    "choose-confirm": "CONFIRM",
    "pv-m-number": "PV Module Number :",
    "pv-ms-number": "PV Module Serie Number :",
    "pv-mp-number": "PV Module Parallel Number :",
    "b-number": "Battery Number :",
    "b-s-number": "Battery Serie Number :",
    "b-p-number": "Battery Parallel Number :",
    ond: "Inverter :",
    "cable-length": "Cable length in m",
    "cable-btn": "START CABLE SIZING",
    "size-cable": "CABLE SIZING",
    "cable-section": "Cable Section :",
    "pdf-btn": "GENERATE RESULTS AS A PDF FILE",
  },
  fr: {
    "landing-heading": "Bienvenue à PV Sizer",
    "landing-text": `Le dimensionnement correct d'une installation est une étape essentielle à maîtriser, pour cela, nous avons créé une application web pour réaliser un dimensionnement de système PV simplement en insérant votre emplacement et les charges souhaitées et vous, facile à utiliser avec des résultats précis`,
    "start-btn": `Commencer Le Dimensionnement`,
    "about-btn": `A Propos De Notre Travail`,
    "about-heading": "Notre Travail",
    "about-text": `Notre travail consiste à réaliser une interface pour le dimensionnement des installations photovoltaïque autonomes dans n'importe quel lieu au monde, on a utilisé le HTML comme langage de rendu et le JavaScript pour recevoir et gérer les données et faire les calculs.
    Le client doit introduire la localisation où il veut installer réaliser son installation, le nombre de jours d’autonomie et ses charges avec leurs puissances, le temps d’utilisation journalière.
    Après on a utilisé un API (Application Programming Interface) pour récupérer la latitude et la longitude du lieu introduit avec lesquelles on aura l’ensoleillement global journalier de la part d’un autre API aussi spécialisé dans ce domaine.`,
    "code-btn": "Voir Le Code",
    made: "Realisé par Zakaria BOURENANE & Yanis BENMEZIANE",
    copy: `TOUT LES DROITS SONT RESERVES 2020 <i class="fa fa-copyright" aria-hidden="true"></i>`,
    location: "Indroduire votre localisation",
    "location-input": "Localisation",
    days: "Introduire nombre de jours d'autonomie",
    "days-input": "Jours",
    add: "AJOUTER UNE CHARGE",
    del: "SUPPRIMER UNE CHARGE",
    submit: "COMMENCER",
    number: "Nombre (ex : 2)",
    power: "Puissance D'une Charge en Watt (ex : 120)",
    time: "Durée D'utilisation (ex : 3)",
    angle: "Angle D'Inclination :",
    orientation: "Orientation :",
    "first-irradiance": "Irradiation Solaire Le ",
    "second-irradiance": "Irradiation Solaire Le ",
    energy: "Energie Consomée D'une journée :",
    "d-power": "Puissance Consomée D'une journée :",
    "pv-power": "Puissance Crete :",
    "pv-battery": "Capacité Des Batteries :",
    "choose-1": "Choisissez votre module PV :",
    "choose-2": "Choisissez votre modele de batterie :",
    "choose-confirm": "CONFIRMER",
    "pv-m-number": "Nombre De Module PV :",
    "pv-ms-number": "Nombre De Module PV En Serie :",
    "pv-mp-number": "Nombre De Module PV En parallele :",
    "b-number": "Nombre De Batteries :",
    "b-s-number": "Nombre De Batteries En serie :",
    "b-p-number": "Nombre De Batteries En Parallele :",
    ond: "Onduleur :",
    "cable-length": "Longueur d'un cable en m",
    "cable-btn": "COMMENCER LE DIMENSIONNEMENT DES CABLES",
    "size-cable": "DIMENSIONNEMENT DES CABLES",
    "cable-section": "Section De Cable :",
    "pdf-btn": "GENERER LES RESULTATS COMME FICHER PDF",
  },
};
